### PR TITLE
Add asset-packagist repository and config.

### PR DESCRIPTION
**Pull request by weitzman**
Issue: https://www.drupal.org/node/2916058

To test, I cloned this repo, ran composer install, and then `composer require bower-asset/dropzone`. Make sure new code is in web/libraries, not vendor/bower-asset

### CODE REVIEW

**Comment by bojanz** [comment]
Thanks! Code looks good. Can we just clarify in the readme that we're talking about JS libraries? It might not be immediately obvious, many refer to PHP packages as libraries as well.

**Comment by mglaman** [comment]
Well anything front-end :) not just JS

**Comment by weitzman** [comment]
Clarified a bit.

**Comment by bojanz** [comment]
Thank you!

**Pull request merged**
